#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."

export PYTHONWARNINGS="ignore:Unverified HTTPS request"
python3 ../app.py $@
